config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root 'items#index'
      
      resources :items do
        get :refresh, :on => :member
      end
    end

    unauthenticated do
      root 'devise/sessions#new'
    end
    
    authenticate :user, ->(user) { user.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :listings, :dependent => :destroy
  has_many :notifications, :dependent => :destroy

  scope :by_user, -> (user) { where(:user_id => user.id) }

  validates :name, :presence => true
  validate :valid_url, :supported_url, :has_query_params

  SUPPORTED_URLS = [::Ksl::AutoClient::REGEX_MATCHER, ::Ksl::ClassifiedClient::REGEX_MATCHER].freeze

  def update_listings
    new_listings = get_listings
    new_listings_links = new_listings.map(&:link)
    existing_listings = listings.where(:link => new_listings_links, :item_id => id)

    new_listings.reject! do |new_listing|
      existing_listings.any? do |existing_listing|
        existing_listing.link == new_listing.link
      end
    end

    new_listings.each do |new_listing|
      new_listing.item_id = id
      new_listing.save
    end
  end

  private

  def get_listings
    client = infer_client
    client = client.new(search_url)
    client.listings
  end

  def has_query_params
    query_params = parsed_query_params
    query_params.reject! { |k,_v| k == "sort"}
    return if query_params.present?

    errors.add(:search_url, "Doesn't look like your URL is searching for anything...")
  end

  def infer_client
    case search_url
    when ::Ksl::AutoClient::REGEX_MATCHER
      ::Ksl::AutoClient
    when ::Ksl::ClassifiedClient::REGEX_MATCHER
      ::Ksl::ClassifiedClient
    else
      raise "Unsupported URL: #{search_url}"
    end
  end

  def parsed_query_params
    Rack::Utils.parse_nested_query(URI.parse(search_url).query)
  rescue ::URI::InvalidURIError
    {}
  end

  def supported_url
    return if SUPPORTED_URLS.any? { |supported_url| supported_url =~ search_url }
    errors.add(:search_url, "We don't support notifications from this site yet.")
  end

  def valid_url
    return if search_url =~ URI.regexp
    errors.add(:search_url, "Invalid URL. Make sure you type in a fully qualified URL.")
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to  :item
  has_many :notifications, :dependent => :destroy

  after_commit :create_notification, :on => [:create]

  monetize :price_cents

  private

  def create_notification
    user_id = item.user_id
    item_id = item.id

    ::Notification.create(:listing_id => id, :user_id => user_id, :item_id => item_id)
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :item
  belongs_to :listing
  belongs_to :user

  scope :undelivered_emails, -> { where(:emailed => [false, nil]) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notifications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_raven_context

  private
  
  def set_raven_context
    Raven.user_context(id: session[:current_user_id]) # or anything else in session
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = ::Item.by_user(current_user)
  end

  def show
    @item = ::Item.by_user(current_user).find(params[:id])
    @listings = @item.listings.order('id ASC')
  end

  def new
    @item = ::Item.new
  end

  def create
    @item = ::Item.new(item_create_params)

    if @item.save
      flash[:notice] = "Item successfuly created"
      redirect_to(@item)
    else
      flash[:alert] = @item.errors.messages
      render :new
    end
  end

  def destroy
    @item = ::Item.by_user(current_user).find(params[:id])
    @item.destroy
 
    redirect_to items_path
  end

  def refresh
    @item = ::Item.by_user(current_user).find(params[:id])
    ::ScrapeItemWorker.perform_async(@item.id)
    flash[:notice] = "Updating item..."
    redirect_to @item
  end

  private

  def item_create_params
    params.require(:item).permit(:name, :search_url).merge(
      :user_id => current_user.id
    )
  end

  def item_find_params
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'is-active' : ''

    link_to link_text, link_path, :class => "navbar-item #{class_name}"
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<div class="section">
  <div class="level">
    <div class="level-left"></div>
    <div class="level-right">
      <%= link_to "Add an item", new_item_path, :class => "level-item button is-primary" %>
    </div>
  </div>
  <div>
    <% @items.each do |item| %>
      <%= link_to item do %>
        <div class="box">
          <%= item.name %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<%= form_for @item do |f| %>
  <div class="field">
    <%= f.label :name, :class => "label" %>
    <div class="control">
      <%= f.text_field :name, :class => "input" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :search_url, :class => "label" %>
    <div class="control">
      <%= f.text_field :search_url, :class => "input" %>
    </div>
  </div>

  <%= f.submit :class => "button is-primary" %>
<% end %>

app/views/items/show.html.erb
<div class="section">
  <div>
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <h1 class="title"><%= @item.name %></h1>
        </div>
      </div>
      <div class="level-right">
        <div class="level-item">
          <%= link_to "Refresh", refresh_item_path(@item), :class => "button" %>
        </div>
        <div class="level-item">
          <%= link_to "Delete", item_path(@item), :method => :delete, :class => "button is-danger" %>
        </div>
      </div>
    </div>
    <% @listings.each do |listing| %>
      <div class="box">
        <article class="media">
          <div class="media-left">
            <figure class="image is-128x128">
              <%= image_tag listing.photo_url if listing.photo_url %>
            </figure>
          </div>
          <div class="media-content" >
            <div class="content">
              <p>
                <strong><%= listing.title %></strong>
                <small><%= humanized_money_with_symbol listing.price %></small>
                <br>
                <%= listing.short_description %>
            </div>
            <nav class="level is-mobile">
              <div class="level-left">
                <%= link_to "Link", listing.link, :class => "level-item" %>
              </div>
            </nav>
          </div>
        </article>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar">
  <div class="navbar-brand">
    <%= link_to "Ksl Notifier", root_path, :class => "navbar-item" %>
  </div>

  <div class="navbar-burger burger" data-target="navMenubd">
  </div>

  <div id="navMenubd" class="navbar-menu">
    <div class="navbar-start">
        <%= nav_link "Items", items_path %>

    </div>

    <div class="navbar-end">
      <div class="navbar-item has-dropdown is-hoverable">
        <%= render "layouts/nav/user_dropdown" %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KslNotifier</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <% if notice %>
      <div class="notification is-primary">
        <button class="delete"></button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert %>
      <div class="notification is-warning">
        <button class="delete"></button>
        <%= alert %>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/nav/_user_dropdown.html.erb
<% if current_user %>
  <div class="navbar-link has-dropdown is-right is-hoverable">
    <%= link_to "Profile", edit_user_registration_path, :class => "navbar-item" %>
    <div class="navbar-dropdown">
      <%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => "navbar-item"%>
    </div>
  </div>
<% else %>
  <div class="navbar-item">
    <%= link_to "Login", new_user_session_path %>
  </div>
<% end %>
</div>